#!/usr/bin/env php
<?php

require_once 'init.php';

$helperSet = new \Symfony\Component\Console\Helper\HelperSet(array(
	'connection' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper($container->get('connection')),
	'dm' => new \Doctrine\ODM\MongoDB\Tools\Console\Helper\DocumentManagerHelper($container->get('odm')),
	'em' => new \Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper($container->get('em')),
));

$app = new Symfony\Component\Console\Application('Fuga CMS Console');
$app->setCatchExceptions(true);
$app->setHelperSet($helperSet);
$app->addCommands(array(
	new \Fuga\Component\Install\FixCommand(),
	new \Fuga\Component\Install\ConfigCommand(),
	new \Doctrine\DBAL\Tools\Console\Command\ImportCommand(),
	new \Doctrine\DBAL\Tools\Console\Command\RunSqlCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\QueryCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateDocumentsCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateRepositoriesCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateProxiesCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateHydratorsCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\ClearCache\MetadataCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\CreateCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\UpdateCommand(),
	new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\DropCommand(),
	new \Doctrine\ORM\Tools\Console\Command\GenerateEntitiesCommand(),
	new \Doctrine\ORM\Tools\Console\Command\GenerateProxiesCommand(),
	new \Doctrine\ORM\Tools\Console\Command\GenerateRepositoriesCommand(),
	new \Doctrine\ORM\Tools\Console\Command\InfoCommand(),
	new \Doctrine\ORM\Tools\Console\Command\MappingDescribeCommand(),
	new \Doctrine\ORM\Tools\Console\Command\RunDqlCommand(),
	new \Doctrine\ORM\Tools\Console\Command\ValidateSchemaCommand(),
	new \Doctrine\ORM\Tools\Console\Command\SchemaTool\CreateCommand(),
	new \Doctrine\ORM\Tools\Console\Command\SchemaTool\DropCommand(),
	new \Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand(),
));
$app->run();